---
batch_size: 1
debug: false
eval_batch_size: 1
eval_epoch_length: null
filename_prefix: training
log_every_iters: 10
lr: 0.0001
max_epochs: 30
model_name: Wav2Vec
model_save_path: ./checkpoints
n_saved: 2
num_workers: 4
output_dir: ./logs
patience: 3
save_every_iters: 500
seed: 42
train_epoch_length: null
use_amp: false